name: Generate Pac-Man Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake (pacman style)
        uses: Platane/snk@v3
        with:
          github_user_name: tom-toupence
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-dark
            dist/pacman-contribution-graph-light.svg?palette=github-light

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
